//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int CompanyID { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Expenses { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
